information:
  - info: China, Shenyang
    icon: "fa-solid fa-house-chimney fa-fw"
  - info: Japan, Tokyo
    icon: "fa-solid fa-map-pin fa-fw"
  - info: >
      <a href="https://www.u-tokyo.ac.jp/ja/index.html">UTokyo</a>,
      <a href="https://www.is.s.u-tokyo.ac.jp">IS</a>
      (BSc 2019-2023)
    icon: "fa-solid fa-building fa-fw"
  - info: >
      <a href="https://www.u-tokyo.ac.jp/ja/index.html">UTokyo</a>,
      <a href="https://www.is.s.u-tokyo.ac.jp">CS</a>
      (MSc 2023-2025)
    icon: "fa-solid fa-building fa-fw"
  - info: >
      <a href="https://www.u-tokyo.ac.jp/ja/index.html">UTokyo</a>,
      <a href="https://www.is.s.u-tokyo.ac.jp">CS</a>
      (PhD 2025-)
    icon: "fa-solid fa-building fa-fw"
  - info: <a href="mailto:pengao@is.s.u-tokyo.ac.jp">pengao[at]is.s.u-tokyo.ac.jp</a>
    icon: "fa-solid fa-envelope fa-fw"
  - info: >
      <a href="https://github.com/PENG-AO">Github</a>,
      <a href="https://leetcode.cn/u/peng_ao">LeetCode</a>
    icon: "fa-solid fa-handshake fa-fw"

identities:
  - info: Professional student
    icon: "fa-solid fa-graduation-cap fa-fw"
  - info: Perfectionist coder
    icon: "fa-solid fa-coffee fa-fw"
  - info: Optimistic reader
    icon: "fa-solid fa-book-reader fa-fw"
  - info: Lite bodybuilder
    icon: "fa-solid fa-dumbbell fa-fw"
  - info: Inquisitive traveler
    icon: "fa-solid fa-compass fa-fw"
  - info: Amateur photographer
    icon: "fa-solid fa-camera fa-fw"

hobbies:
  - info: Coding
    icon: "fa-solid fa-laptop-code fa-fw"
  - info: Reading
    icon: "fa-solid fa-book fa-fw"
  - info: Traveling
    icon: "fa-solid fa-person-hiking fa-fw"

friends:
  - name: CHEN Ziheng
    link: https://zoooooone.github.io
    info: Blog
  - name: GAO Suihan
    link: https://github.com/TimG233
    info: GitHub

skills:
  - info: c
    color: "A8B9CC"
  - info: cplusplus
    color: "00599C"
  - info: python
    color: "3776AB"
  - info: gnubash
    color: "4EAA25"
  - info: ocaml
    color: "EC6813"
  - info: html5
    color: "E34F26"
  - info: sass
    color: "CC6699"
  - info: javascript
    color: "F7DF1E"
  - info: latex
    color: "008080"
  - info: markdown
    color: "000000"
